### ISSUE TITLE
Can't fetch users

### ISSUE THREAD

**Issue by YumYummity** [shayypy/guilded.py#63]
**Describe the bug**
Fetch users will no longer work.

**To Reproduce**
`await bot.fetch_user("valid user id")`

**Expected behavior**
To get a User object.

**Actual behavior**
A error occurs.
```python
Traceback (most recent call last):
  File "C:\Development\Python\Python3.10.6\lib\site-packages\guilded\client.py", line 450, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\YumYummity\Desktop\bot\guilded\Crystal\COGS\logging.py", line 1652, in on_ban_delete
    if server_data.logging.logSettings.enabled:
  File "C:\Development\Python\Python3.10.6\lib\site-packages\guilded\client.py", line 657, in getch_user
    return self.get_user(user_id) or await self.fetch_user(user_id)
  File "C:\Development\Python\Python3.10.6\lib\site-packages\guilded\client.py", line 642, in fetch_user
    data = await self.http.get_user(user_id)
  File "C:\Development\Python\Python3.10.6\lib\site-packages\guilded\http.py", line 645, in request
    raise BadRequest(response, data)
guilded.errors.BadRequest: 400 (BadRequest): You can currently only request your own user ID
```

**Environment**
 - OS: Windows 11
 - Python version (make sure you're using >=3.8): 3.10.6
 - Library version: 1.14.0a

Quick note: I am unable to talk in the Discord server and cannot figure out how to verify (I have unverified role-)

**Comment by shayypy** [comment]
Can you show the entire traceback? There should be another one above this which caused it to fall back to the bot API. The [endpoint](https://www.guilded.gg/docs/api/users/UserRead) has never allowed non-client user fetching which is why the library prefers the user API endpoint.

**Comment by YumYummity** [comment]
> Can you show the entire traceback? There should be another one above this which caused it to fall back to the bot API. The [endpoint](https://www.guilded.gg/docs/api/users/UserRead) has never allowed non-client user fetching which is why the library prefers the user API endpoint.

Sadly, that _is_ the entire traceback.

Reproducible by simply having a command with `await bot.fetch_user("id")`

**Comment by shayypy** [comment]
Yeah it looks like that traceback is from an older version. That should no longer happen as of [this commit](https://github.com/shayypy/guilded.py/commit/3c6537aaa5b0af14982d2f988f071e99a2a71db2). 

Anyway, I just tested it myself and the method appears to work perfectly well on the latest github version:
```py
# await client.fetch_user('EdVMVKR4')
2024-11-17 09:55:02,573:DEBUG:guilded.http: GET https://www.guilded.gg/api/users/EdVMVKR4/profilev3 with data None, headers {'User-Agent': 'guilded.py/1.14.0a (https://github.com/shayypy/guilded.py) Python/3.12 aiohttp/3.9.5', 'x-guilded-bot-api-use-official-markdown': 'true'}, has returned 200
2024-11-17 09:55:02,575:DEBUG:guilded.http: Response provided a CDN token, storing
2024-11-17 09:55:02,575:DEBUG:guilded.http: GET https://www.guilded.gg/api/users/EdVMVKR4/profilev3 has received {'id': 'EdVMVKR4', 'name': 'shay', 'subdomain': 'shay', ...}
# returns a User
```

Closing this as can't repro but I am still curious why this is happening for you. Also, you should be able to talk in the discord server now.

**Comment by shayypy** [comment]
Actually.. I just noticed that it looks like you're calling `getch_user` in an `on_ban_delete` callback. Can you show a snippet from your `COGS/logging.py` file?

**Comment by YumYummity** [comment]
> Actually.. I just noticed that it looks like you're calling `getch_user` in an `on_ban_delete` callback. Can you show a snippet from your `COGS/logging.py` file? Also be sure that you are running the latest version of your code since it looks like the file might have been modified but not reloaded.

The 403 forbidden was caused due to not upgrading; still unsure about the 400.

The code in question can be found https://github.com/EcoNuker/Crystal/blob/main/COGS/logging.py#L1655
